name: my_project

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ^3.5.4
    dependencies:
      flutter_riverpod: ^2.6.1
      riverpod_annotation: ^2.6.1
    
    dev_dependencies:
      build_runner: ^2.4.13
      custom_lint: ^0.7.0
      melos: ^6.2.0
      riverpod_generator: ^2.6.3
      riverpod_lint: ^2.6.3